---
- name: put Tor config file in place
  template: >
    src=torrc.j2
    dest=/etc/tor/torrc
    backup=yes
    owner={{ tor_user }}
    mode=0644
  register: tor_conf
  tags:
    - configure
    - files

- name: create/ensure correct directory permissions
  file: >
    path={{ item }}
    recurse=yes
    state=directory
    owner={{ tor_user }}
    group={{ tor_user }}
    mode=0750
  with_items:
    -  /var/log/tor
    -  /var/lib/tor
  tags:
    - configure
    - dirs

- name: start Tor service if not yet running
  service: >
    name=tor
    state=started
    enabled=yes
  tags:
    - configure
    - service

- name: restart Tor service if Tor config was changed
  service: >
    name=tor
    state=reloaded
  when: tor_conf.changed == True
  tags:
    - configure
    - service
